
$(function(){
var h='<div id="sicklyBanner"><style>#sicklyBanner p { margin:0; padding:0; color:#000; } #sicklyBanner a, #sicklyBanner a:hover, #sicklyBanner a:hover, #sicklyBanner a:visited, #sicklyBanner a:active { text-decoration:none; color:#000; } .sicklyBox1 { min-width:900px; position:fixed; right:0; left:0; border-bottom:3px solid #99999955; border-bottom:3px solid rgba(153,153,153,0.3); } .sicklyBox2 { position:relative; background-color:#e6e6e6e6; background-color:rgba(230,230,230,0.9); padding:11px 18px 8px 18px; border-bottom:1px solid #999; } .sicklySchoolLogo { float:left; max-width:100px; max-height:62px; margin-right:12px; } .sicklyText { display:inline-block; min-height:62px; } .sicklyRight { position:absolute; bottom:10px; right:32px; text-align:right; } a.sicklyDismiss:hover { text-decoration:underline !important; } .sicklyButton { margin-top:2px; background:url(https://www.sickly.org/im/widgets/btn-bg.png) repeat-x; padding:6px; width:276px; } .sicklyButton a { border:1px solid #0065BD99; border:1px solid rgba(0,101,189,0.6); background-color:#4494DB99; background-color:rgba(68,148,219,0.6); display:block; -moz-transition:all 0.3s ease-in-out; -webkit-transition:all 0.3s ease-in-out; -o-transition:all 0.3s ease-in-out; transition:all 0.3s ease-in-out; } .sicklyButton a:hover { background-color:#4494DBE7; background-color:rgba(68,148,219,0.9); } .sicklyButton img { width:247px; height:23px; padding:5px 13px 5px 14px } .sicklySpacer { height:94px; }</style><div class="sicklyBox1"><div class="sicklyBox2"><div class="sicklyLeft"><img class="sicklySchoolLogo" src="https://www.sickly.org/im/widgets/davigdor-logo.png"/><div class="sicklyText"><p style="font-size:19px;font-weight:bold;">Is your child ill?</p><p style="font-size:14px">If your child’s ill and will be absent from school, you need to to tell us.<br/>We use a service called&nbsp;<b>Sickly</b>&nbsp;which makes it easy.</p></div></div><div class="sicklyRight"><a class="sicklyDismiss" href="#">x&nbsp;Not right now</a><div class="sicklyButton"><a href="https://www.sickly.org/"><img src="https://www.sickly.org/im/widgets/btn-label.png"/></a></div></div></div></div><div class="sicklySpacer"/></div>';
window.setTimeout(function(){
  var e=$(h).prependTo('body');
  e.children('div').hide().slideDown(300);
  $('.sicklyDismiss').click(function(){e.children('div').slideUp(300)});
},1000);
});
            